context("sampling")
setwd("../..")
BMI <- BMI(bugdata)
BMIagg <- aggregate(BMI)

test_that("sampling returns data", {
  expect_that(nrow(sample(BMIagg))>0, is_true())
})

BMIprc <- sample(BMIagg)

test_that("Subsampling successful", {
  expect_that(!is.null(BMIprc$BAResult.subsample), is_true())
  expect_that(length(which(BMIprc$BAResult.subsample>500)), equals(0))
})

test_that("Generic function", {
  expect_that(length(sample(1:10)), equals(10))
})

BMIprc <- sample(BMIagg)

context("metrics")

test_that("All metrics calculation", {
  expect_that(nrow(BMIall(BMIagg))>0, is_true())
  expect_that(nrow(BMIall(BMIprc))>0, is_true())  
})

x <- BMIagg

test_that("Individual metrics for BMIagg", {
  expect_that(nrow(Acari_Percent(x))>0, is_true())
  expect_that(nrow(Acari_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Acari_Taxa(x))>0, is_true())
  expect_that(nrow(Amphipoda_Percent(x))>0, is_true())
  expect_that(nrow(Burrower_Percent(x))>0, is_true())
  expect_that(nrow(Burrower_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Burrower_Taxa(x))>0, is_true())
  expect_that(nrow(CFCG_Percent(x))>0, is_true())
  expect_that(nrow(CFCG_PercentTaxa(x))>0, is_true())
  expect_that(nrow(CFCG_Taxa(x))>0, is_true())
  expect_that(nrow(Chironomidae_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Chironomidae_Taxa(x))>0, is_true())
  expect_that(nrow(Chironominae_Percent(x))>0, is_true())
  expect_that(nrow(Chironominae_PercentOfMidges(x))>0, is_true())
  expect_that(nrow(Climber_Percent(x))>0, is_true())
  expect_that(nrow(Climber_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Climber_Taxa(x))>0, is_true())
  expect_that(nrow(Clinger_Percent(x))>0, is_true())
  expect_that(nrow(Clinger_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Clinger_Taxa(x))>0, is_true())
  expect_that(nrow(Coleoptera_Percent(x))>0, is_true())
  expect_that(nrow(Coleoptera_PercentTaxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Coleoptera_PercentTaxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Coleoptera_Taxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Coleoptera_Taxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Crustacea_Percent(x))>0, is_true())
  expect_that(nrow(Diptera_Percent(x))>0, is_true())
  expect_that(nrow(Diptera_PercentTaxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Diptera_PercentTaxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Diptera_Taxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Diptera_Taxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(EPT_Percent(x))>0, is_true())
  expect_that(nrow(EPT_PercentTaxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(EPT_PercentTaxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(EPT_Taxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(EPT_Taxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Ephemeroptera_Percent(x))>0, is_true())
  expect_that(nrow(Ephemeroptera_PercentTaxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Ephemeroptera_PercentTaxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Ephemeroptera_Taxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Ephemeroptera_Taxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Intolerant_Percent(x))>0, is_true())
  expect_that(nrow(Intolerant_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Intolerant_Taxa(x))>0, is_true())
  expect_that(nrow(Invasive_Percent(x))>0, is_true())
  expect_that(nrow(Invasive_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Invasive_Taxa(x))>0, is_true())
  expect_that(nrow(Noninsect_Percent(x))>0, is_true())
  expect_that(nrow(Noninsect_PercentTaxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Noninsect_PercentTaxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Noninsect_Taxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Noninsect_Taxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Orthocladiinae_PercentOfMidges(x))>0, is_true())
  expect_that(nrow(Ostracoda_Percent(x))>0, is_true())
  expect_that(nrow(Plecoptera_Percent(x))>0, is_true())
  expect_that(nrow(Plecoptera_PercentTaxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Plecoptera_PercentTaxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Plecoptera_Taxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Plecoptera_Taxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Predator_Percent(x))>0, is_true())
  expect_that(nrow(Predator_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Predator_Taxa(x))>0, is_true())
  expect_that(nrow(Scraper_Percent(x))>0, is_true())
  expect_that(nrow(Scraper_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Scraper_Taxa(x))>0, is_true())
  expect_that(nrow(Shredder_Percent(x))>0, is_true())
  expect_that(nrow(Shredder_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Shredder_Taxa(x))>0, is_true())
  expect_that(nrow(Shannon_Diversity(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Shannon_Diversity(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Simpson_Diversity(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Simpson_Diversity(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Swimmer_Percent(x))>0, is_true())
  expect_that(nrow(Swimmer_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Swimmer_Taxa(x))>0, is_true())
  expect_that(nrow(Tanypodinae_Percent(x))>0, is_true())
  expect_that(nrow(Tanypodinae_PercentOfMidges(x))>0, is_true())
  expect_that(nrow(ToleranceValue(x))>0, is_true())
  expect_that(nrow(Tolerant_Percent(x))>0, is_true())
  expect_that(nrow(Tolerant_PercentTaxa(x))>0, is_true())
  expect_that(nrow(Tolerant_Taxa(x))>0, is_true())
  expect_that(nrow(Total_Taxa(x))>0, is_true())
  expect_that(nrow(Trichoptera_Percent(x))>0, is_true())
  expect_that(nrow(Trichoptera_PercentTaxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Trichoptera_PercentTaxa(x, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Trichoptera_Taxa(x, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Trichoptera_Taxa(x, level="SAFIT2"))>0, is_true())
})

y <- BMIprc

test_that("Individual metrics for BMIprc", {
  expect_that(nrow(Acari_Percent(y))>0, is_true())
  expect_that(nrow(Acari_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Acari_Taxa(y))>0, is_true())
  expect_that(nrow(Amphipoda_Percent(y))>0, is_true())
  expect_that(nrow(Burrower_Percent(y))>0, is_true())
  expect_that(nrow(Burrower_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Burrower_Taxa(y))>0, is_true())
  expect_that(nrow(CFCG_Percent(y))>0, is_true())
  expect_that(nrow(CFCG_PercentTaxa(y))>0, is_true())
  expect_that(nrow(CFCG_Taxa(y))>0, is_true())
  expect_that(nrow(Chironomidae_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Chironomidae_Taxa(y))>0, is_true())
  expect_that(nrow(Chironominae_Percent(y))>0, is_true())
  expect_that(nrow(Chironominae_PercentOfMidges(y))>0, is_true())
  expect_that(nrow(Climber_Percent(y))>0, is_true())
  expect_that(nrow(Climber_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Climber_Taxa(y))>0, is_true())
  expect_that(nrow(Clinger_Percent(y))>0, is_true())
  expect_that(nrow(Clinger_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Clinger_Taxa(y))>0, is_true())
  expect_that(nrow(Coleoptera_Percent(y))>0, is_true())
  expect_that(nrow(Coleoptera_PercentTaxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Coleoptera_PercentTaxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Coleoptera_Taxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Coleoptera_Taxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Crustacea_Percent(y))>0, is_true())
  expect_that(nrow(Diptera_Percent(y))>0, is_true())
  expect_that(nrow(Diptera_PercentTaxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Diptera_PercentTaxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Diptera_Taxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Diptera_Taxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(EPT_Percent(y))>0, is_true())
  expect_that(nrow(EPT_PercentTaxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(EPT_PercentTaxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(EPT_Taxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(EPT_Taxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Ephemeroptera_Percent(y))>0, is_true())
  expect_that(nrow(Ephemeroptera_PercentTaxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Ephemeroptera_PercentTaxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Ephemeroptera_Taxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Ephemeroptera_Taxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Intolerant_Percent(y))>0, is_true())
  expect_that(nrow(Intolerant_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Intolerant_Taxa(y))>0, is_true())
  expect_that(nrow(Invasive_Percent(y))>0, is_true())
  expect_that(nrow(Invasive_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Invasive_Taxa(y))>0, is_true())
  expect_that(nrow(Noninsect_Percent(y))>0, is_true())
  expect_that(nrow(Noninsect_PercentTaxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Noninsect_PercentTaxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Noninsect_Taxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Noninsect_Taxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Orthocladiinae_PercentOfMidges(y))>0, is_true())
  expect_that(nrow(Ostracoda_Percent(y))>0, is_true())
  expect_that(nrow(Plecoptera_Percent(y))>0, is_true())
  expect_that(nrow(Plecoptera_PercentTaxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Plecoptera_PercentTaxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Plecoptera_Taxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Plecoptera_Taxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Predator_Percent(y))>0, is_true())
  expect_that(nrow(Predator_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Predator_Taxa(y))>0, is_true())
  expect_that(nrow(Scraper_Percent(y))>0, is_true())
  expect_that(nrow(Scraper_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Scraper_Taxa(y))>0, is_true())
  expect_that(nrow(Shredder_Percent(y))>0, is_true())
  expect_that(nrow(Shredder_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Shredder_Taxa(y))>0, is_true())
  expect_that(nrow(Shannon_Diversity(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Shannon_Diversity(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Simpson_Diversity(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Simpson_Diversity(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Swimmer_Percent(y))>0, is_true())
  expect_that(nrow(Swimmer_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Swimmer_Taxa(y))>0, is_true())
  expect_that(nrow(Tanypodinae_Percent(y))>0, is_true())
  expect_that(nrow(Tanypodinae_PercentOfMidges(y))>0, is_true())
  expect_that(nrow(ToleranceValue(y))>0, is_true())
  expect_that(nrow(Tolerant_Percent(y))>0, is_true())
  expect_that(nrow(Tolerant_PercentTaxa(y))>0, is_true())
  expect_that(nrow(Tolerant_Taxa(y))>0, is_true())
  expect_that(nrow(Total_Taxa(y))>0, is_true())
  expect_that(nrow(Trichoptera_Percent(y))>0, is_true())
  expect_that(nrow(Trichoptera_PercentTaxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Trichoptera_PercentTaxa(y, level="SAFIT2"))>0, is_true())
  expect_that(nrow(Trichoptera_Taxa(y, level="SAFIT1"))>0, is_true())
  expect_that(nrow(Trichoptera_Taxa(y, level="SAFIT2"))>0, is_true())
})